version: '3'
services:
  redis:
    image: redis:4
    container_name: redis4.local
    ports:
      - "6379:6379"
    networks:
      - app_net

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/var/www/app"
    ports:
      - "80:3000"
    depends_on:
      - redis
    links:
      - "redis:redis4.local"
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis.local:6379/0
      DOCKERIZED: 'true'
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
